### PR TITLE
Subject: changing the C++17 build flag

### PR DESCRIPTION
**Pull request by stedsome**
Signed-off-by: Yifan Yang <needyyang@google.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by rebello95** [comment]
Thanks for this! Looks like our main branch is a little bit ahead of the envoy ref in this PR. However, would it make sense to bump the `copts` here to switch us to C++17?

https://github.com/lyft/envoy-mobile/blob/da521e4ab4ae631e5884eca0c11b5db22e5f0444/library/common/BUILD#L48

**Comment by stedsome** [comment]
@rebello95 yes just found out the submodule is updated already haha. I will make that change instead. My original plan was to separate those into two PRs.

**Comment by rebello95** [comment]
Awesome!

**Comment by rebello95** [comment]
Please be sure to merge master into your branch as well

**Comment by rebello95** [comment]
Thank you!

**Pull request merged**
