### PR TITLE
ci: add job to publish iOS release artifact on merge to master

### PR DESCRIPTION
**Pull request by rebello95**
Adds a job that runs on master and builds/uploads a zip artifact of the `Envoy.framework` for iOS using the release configurations. This should make it easier for consumers to utilize the most recent iOS versions of Envoy Mobile.

Resolves https://github.com/lyft/envoy-mobile/issues/547.

Tested against this PR, which resulted in the expected artifacts being uploaded successfully:

Screen Shot 2019-10-30 at 2 15 05 PM

Signed-off-by: Michael Rebello <me@michaelrebello.com>

### CODE REVIEW

**Comment by junr03** [comment]
I thought at some point we had filters on the aar run to only execute when the common or android code was changed in order to prevent wasted CI time on iOS or documentation changes. Do we still want to do something like that, or do we want to create fresh artifacts on _every_ commit to master?

**Comment by rebello95** [comment]
@junr03 please see https://github.com/lyft/envoy-mobile/pull/561 for context 😃

**Comment by junr03** [comment]
> @junr03 please see #561 for context 😃

I see. I guess that is fair. Unfiltered artifacts makes a better experience for maintainers and for users, even if it means burning a bit more CI time.

**Comment by rebello95** [comment]
> I see. I guess that is fair. Unfiltered artifacts makes a better experience for maintainers and for users, even if it means burning a bit more CI time.

Right. I'd rather we optimize for the CI experience we want and obtain the machines as necessary rather than limit our functionality up front

**Pull request merged**
