### PR TITLE
Work around BoringSSL bitcode linker warning

### PR DESCRIPTION
**Pull request by keith**
When linking envoy-mobile to an iOS app that ships with bitcode, you get
these warnings from the linker:

```
ld: warning: Linker asked to preserve internal global: 'sk_CRYPTO_BUFFER_call_free_func'
ld: warning: Linker asked to preserve internal global: 'sk_X509_call_free_func'
ld: warning: Linker asked to preserve internal global: 'sk_X509_call_free_func'
ld: warning: Linker asked to preserve internal global: 'sk_X509_call_free_func'
ld: warning: Linker asked to preserve internal global: 'sk_X509_call_free_func'
```

I have submitted an upstream patch to fix this
https://boringssl-review.googlesource.com/c/boringssl/+/37804 in the
meantime I've applied that patch here.

Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Comment by keith** [comment]
https://github.com/lyft/envoy-mobile/issues/471

**Comment by goaway** [comment]
thanks @keith!

**Comment by keith** [comment]
Lets hold on this until we have some clarity upstream about this fix

**Comment by keith** [comment]
Going to update the upstream conversation but this is fine for now

**Pull request merged**
