### PR TITLE
build: Downgrade xctestrunner

### PR DESCRIPTION
**Pull request by keith**
Signed-off-by: Keith Smiley <keithbsmiley@gmail.com>

### CODE REVIEW

**Comment by keith** [comment]
CI runs on a version of Xcode this doesn't support, so we're kinda stuck here. Locally you can `brew install python@2` and `brew link python@2`

**Comment by buildbreaker** [comment]
Thanks for the workaround @keith

**Comment by buildbreaker** [comment]
I seem to be having an issue locating `python@2` but I ended up doing this: https://stackoverflow.com/questions/60298514/brew-reinstalling-python2

**Comment by buildbreaker** [comment]
Work around works!

**Comment by keith** [comment]
probably `ln -s /usr/bin/python2.7 /usr/local/bin/python2` would be fine too

**Pull request closed without merging**
