### PR TITLE
ci: pin macOS and linux versions

### PR DESCRIPTION
**Pull request by rebello95**
This will prevent machines from switching beneath us.

Signed-off-by: Michael Rebello <me@michaelrebello.com>

### CODE REVIEW

**Comment by rebello95** [comment]
Re-running

**Comment by junr03** [comment]
I am seeing the same failures across all the linux runs when installing deps. I am investigating

**Comment by rebello95** [comment]
Yep, appears to be red on an unrelated PR too: https://github.com/lyft/envoy-mobile/pull/360

**Comment by junr03** [comment]
:/ #351 was all green for the deps. Something must have happened with the mirror they use for package management. I am trying to see if 16.04 has the same issue. If they do I will talk to github/msft people tomorrow.

**Comment by rebello95** [comment]
Sounds good 👍 looks like something's failing to download internally

**Pull request merged**
