### PR TITLE
[Draft] Xcode integration

### PR DESCRIPTION
**Pull request by kastiglione**
This is exploring the possibility of custom Xcode integration.

<details>
<summary>PR Template</summary>
For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]
</details>

### CODE REVIEW

**Comment by kastiglione** [comment]
The initial commit is a very early draft. It builds with bazel, but not tests. Header files are wired up so clicking through to other files works (including Envoy), but I haven't tried autocompletion or importing a bazel built index.

Next steps are to get more use cases, and to support those. This is here for visibility and at some point for people to try.

**Comment by rebello95** [comment]
Thanks for opening this up @kastiglione! I tried generating using the following steps:

- Download index-import from [here](https://github.com/lyft/index-import/releases/tag/5.1.1.3) and copy `index-import` into the base `envoy-mobile` directory
- `brew install xcodegen`
- `xcodegen generate`
- Opening up the `.xcodeproj`

The project looks good, but builds fail (seemingly because it can't find some Objective-C types):

Screen Shot 2019-12-31 at 4 54 01 PM

Any suggestions for something I may have done wrong in my setup?

**Comment by kastiglione** [comment]
Your steps look good. I spent most of my time trying C++, and didn't try the swift. I may need to update the index-import command. I'll open the file from the example and get it working.

**Comment by kastiglione** [comment]
What I've found:

* The build succeeds, the errors in red are from the indexer not the build
* I can jump to definition of the types it's complaining about (`EnvoyEngine`, `EnvoyConfiguration`)

I'll figure out why the indexer is emitting those errors and fix it

**Comment by kastiglione** [comment]
I plan to look again this week.

**Comment by kastiglione** [comment]
My new plan is to look next week.

**Comment by kastiglione** [comment]
I'll reopen at some point (hopefully sooner than later)

**Pull request closed without merging**
