### PR TITLE
java: remove explicit jdk setup

### PR DESCRIPTION
**Pull request by junr03**
Signed-off-by: Jose Nino <jnino@lyft.com>

For an explanation of how to fill out the fields, please see the relevant section
in [PULL_REQUESTS.md](https://github.com/envoyproxy/envoy/blob/master/PULL_REQUESTS.md)

Description:
Risk Level:
Testing:
Docs Changes:
Release Notes:
[Optional Fixes #Issue]
[Optional Deprecated:]

### CODE REVIEW

**Comment by junr03** [comment]
@buildbreaker I noticed you added jdk setup in https://github.com/lyft/envoy-mobile/pull/877 for javadocs, but I think that might be causing issues now against the example apps: https://github.com/lyft/envoy-mobile/runs/782461117#step:8:70 and what is installed in the github actions mac ci agents

**Comment by buildbreaker** [comment]
@junr03 We'll likely get another issue but this looks like a proguard issue with android-30?

A similar issue a few years back: https://github.com/bazelbuild/bazel/issues/3777

**Comment by buildbreaker** [comment]
Likely cause: https://github.com/actions/virtual-environments/pull/1030?

**Comment by buildbreaker** [comment]
Let's try: https://github.com/lyft/envoy-mobile/pull/918?

**Pull request closed without merging**
