### PR TITLE
documentation: update some language

### PR DESCRIPTION
**Pull request by goaway**
Signed-off-by: Mike Schore <mike.schore@gmail.com>

### CODE REVIEW

**Comment by buildbreaker** [comment]
There are some more references here: https://github.com/lyft/envoy-mobile/blob/main/bazel/swift_static_framework.bzl#L139-L141

**Comment by rebello95** [comment]
> There are some more references here: https://github.com/lyft/envoy-mobile/blob/main/bazel/swift_static_framework.bzl#L139-L141

Those are external though, right @buildbreaker?

**Comment by buildbreaker** [comment]
That one is in Envoy Mobile

**Comment by buildbreaker** [comment]
https://github.com/lyft/envoy-mobile/blob/main/docs/root/api/starting_envoy.rst#addstatsdomain -- another within our docs

**Comment by goaway** [comment]
Thanks @rebello95 and @buildbreaker! I updated the documentation example you pointed out, @buildbreaker.

**Pull request merged**
