### PR TITLE
filters: fix kotlin status mapping

### PR DESCRIPTION
**Pull request by goaway**
Description: Adds additional java context layer mapping needed to transform headers.
Risk Level: Moderate
Testing: Local and CI (#1163)

Signed-off-by: Mike Schore <mike.schore@gmail.com>

### CODE REVIEW

**Review by buildbreaker — COMMENTED** [review]
This change is fine but do we have a plan for how we would exercise this change path to avoid regressing in the future?

**Comment by goaway** [comment]
@buildbreaker This adds initial integration coverage: https://github.com/lyft/envoy-mobile/pull/1163

**Comment by goaway** [comment]
Eventually the plan remains to do more in depth coverage via the AssertionFilter.

**Review by buildbreaker — APPROVED** [review]
Sounds good @goaway

**Pull request merged**
