### PR TITLE
platform: add Trailers type for better classification

### PR DESCRIPTION
**Pull request by goaway**
Description: Allows for better scoping of header types; in this case, specifically for advanced filters.
Risk Level: Low
Testing: CI

Signed-off-by: Mike Schore <mike.schore@gmail.com>

### CODE REVIEW

**Review by rebello95 — COMMENTED** [review]
This seems reasonable. Can we update the callbacks on the client / streams as well?

**Comment by goaway** [comment]
@rebello95 I think those are all already correct because they're already specific `Request~` or `Response~` variants.

**Comment by rebello95** [comment]
Ah right, good call

**Review by rebello95 — APPROVED** [review]

**Comment by goaway** [comment]
thanks @rebello95!

**Pull request merged**
